### ISSUE TITLE
Freeze When Writing Large Files

### ISSUE THREAD

**Issue by TOM-BadEN** [ITotalJustice/libhaze#1]
Hello Master, I used the example from your library. From my testing, I found that reading files works very smoothly. Writing small files is fine as well, but when the file is a bit larger — for example, around 400 MB — the program gets stuck at the file creation stage.

I checked the implementation:

```
Result CreateFile(const char* path, s64 size, u32 option) override {
    return fsFsCreateFile(&m_fs, FixPath(path), size, option);
}
```

When I change size to 0, the 400 MB file can be created and written successfully.
However, for even larger files such as 1 GB or 2 GB, it still gets stuck during writing.

I also tried writing in chunks, but it still freezes partway through the process.
At this point, I really don’t know how to proceed, so I’m reaching out to ask for your advice.

**Comment by ITotalJustice** [comment]
CreateFile allocates the file size ahead of time, so it's expected for it to take some time to complete. How long it takes depends on your sd card, how fragmented it is, how big the size is etc.

When you say that it freezes, how long did you wait?

If it's freezing during writing, as in permanently freezing, then sadly i cannot fix this because i do not know what causes it. I have had users randomly have it happen to them, and then when they try again it works. I spent weeks trying to debug it and got nowhere.

**Comment by TOM-BadEN** [comment]
For example, with the 452MB file I tested, if I didn’t set the size of this video file to 0, there would be no response even after waiting for several minutes. I can’t recall the exact length of time, but it was definitely long enough to write a file of over 400MB. However, once I set the size to 0, the transfer would work normally.

Furthermore, transfers of files over 400MB succeeded every single time. But I also tested 1GB and 2GB files: the 1GB ones succeeded occasionally, while the 2GB ones almost always got stuck during the transfer process—for instance, getting stuck at 500MB, 700MB, or 900MB. When the transfer progress freezes midway, if I wait for a few minutes, the connection will likely drop due to a timeout.

**Comment by TOM-BadEN** [comment]
I just tested it with your SP as well, and found the same situation.

**Comment by TOM-BadEN** [comment]
I need to add one more note: I used MTP to transfer files and haven’t tested game installations.

**Comment by ITotalJustice** [comment]
I assume this is windows, right?

Yeah sounds like the bug i mentioned. Like i said, i cannot fix it. If you want to try your hand it, the freeze happens because the usb transfer event never fires, which causes it to hang. It only wakes up because the MTP OS driver kills the transfer. The only reason for the event to not fire means the switch received no data.

Yes Sphaira has the same bug because it uses haze.

Games will also hang, its the same transfer process.

---

Are you using the latest code on github?

**Comment by ITotalJustice** [comment]
The other issue i have in fixing the bug is that i cannot cause the bug to happen. I have ran 100's of tests and it has never happened once for me. This makes it extremely difficult to fix.

**Comment by TOM-BadEN** [comment]
Yes, I'm using Windows 11. 
I used the code from your GitHub repository that was submitted before your latest commit.

**Comment by TOM-BadEN** [comment]
> The other issue i have in fixing the bug is that i cannot cause the bug to happen. I have ran 100's of tests and it has never happened once for me. This makes it extremely difficult to fix.我在修复这个 bug 时遇到的另一个问题是，我无法触发这个 bug。我已经运行了数百次测试，但从未发生过一次。这使得修复它变得极其困难。

That’s so strange. Could it be because you’re not using Windows?

For me, this issue is 100% reproducible.

I’m also wondering if there’s another possibility: could this problem be caused by the fact that my Windows environment is set to Chinese?

I noticed that I can’t use the sample program to create a new folder on Windows, and that’s because the default name for a newly created folder in the Chinese version of Windows is in Chinese.

**Comment by TOM-BadEN** [comment]
> 
> That’s so strange. Could it be because you’re not using Windows?太奇怪了。是不是因为你没用 Windows？
> 
> For me, this issue is 100% reproducible.对我来说，这个问题 100% 可重现。
> 
> I’m also wondering if there’s another possibility: could this problem be caused by the fact that my Windows environment is set to Chinese?我也想知道是否还有另一种可能性：这个问题会不会是由于我的 Windows 环境设置为中文而导致的？
> 
> I noticed that I can’t use the sample program to create a new folder on Windows, and that’s because the default name for a newly created folder in the Chinese version of Windows is in Chinese.我注意到我无法使用示例程序在 Windows 上创建新文件夹，这是因为中文版 Windows 中新建文件夹的默认名称是中文。

I just tried changing the Windows language to English, but the problem hasn't been solved.

**Comment by ITotalJustice** [comment]
> That’s so strange. Could it be because you’re not using Windows?

Yes i do not use windows. I have it in a VM but its very slow / painful to test stuff like this. However i am not blaming the issue on windows because MTP works fine for other devices.

> I’m also wondering if there’s another possibility: could this problem be caused by the fact that my Windows environment is set to Chinese?

No, i don't think so. Users with the same problem had it in English.

The freeze happens here afaik:
https://github.com/ITotalJustice/libhaze/blob/d60ba600c0d6aa23d4028f323372683abca179ab/source/event_reactor.cpp#L51C26-L51C37
it waits for the transfer event to fire, but it never does.

It actually waits on 2 events, a quit event and transfer event. The quit event is only fired when closing libhaze, so that is basically never fired.

Here's the transfer code: https://github.com/ITotalJustice/libhaze/blob/d60ba600c0d6aa23d4028f323372683abca179ab/source/async_usb_server.cpp#L39

This only happens during init: https://github.com/ITotalJustice/libhaze/blob/d60ba600c0d6aa23d4028f323372683abca179ab/source/async_usb_server.cpp#L44, so during a file transfer, this `if ()` is never triggered.

This is the actual transfer code: https://github.com/ITotalJustice/libhaze/blob/d60ba600c0d6aa23d4028f323372683abca179ab/source/async_usb_server.cpp#L52-L59

**Comment by TOM-BadEN** [comment]
You're very welcome for the detailed explanation! I'll keep trying to figure this out.

On top of that, something even weirder just happened—I’m totally confused. I sent the file that I couldn’t transfer/upload to my friend and asked him to test it with SP. It turned out he could transfer/upload it without any problem, but I still can’t.

**Comment by ITotalJustice** [comment]
> I sent the file that I couldn’t transfer/upload to my friend and asked him to test it with SP. It turned out he could transfer/upload it without any problem, but I still can’t.

That's the fun part of the bug. It randomly works 🥲 You can spend weeks trying to fix it, and everyone reports back that it now works for them, success! Well, until someone else reports that it doesn't work for them, and those users that reported it working, well it no longer works for them.

So even if it looks like it's fixed, it probably isn't. It's just magically working, until it doesn't.

---

If you do make any further progress fixing this, or even fixing it entirely, i will be *VERY* happy. If you need help understanding libhaze code / how something works, feel free to ask.

**Comment by TOM-BadEN** [comment]
I really don’t feel I’m up to this,so all I can say is I'll give it a try.

**Comment by TOM-BadEN** [comment]
Here's the even stranger part:
I asked a friend to test a 3GB compressed file. He has two devices—one OLED model and one Lite model. The OLED successfully completed the test all 3 times, but the Lite failed halfway through both of its attempts. As for my own device, it’s a Lite too, and it hasn’t succeeded even once. This is really bizarre.

**Comment by ITotalJustice** [comment]
Does it freeze when you upload to the dev/null folder? It's not slowed down by the sd card write speed and just reads fast as possible.

Is this usb 2.0 or 3.0 connection? You can launch the mtp/usb menu in sphaira to check the real usb connection speed.

**Comment by TOM-BadEN** [comment]
The LITE only has version 2.0,
while its OLED  uses version 3.0.
This file is a single 3GB file.
I directly uploaded it to a random location in the SD card's mount point.
The OLED  had no problems at all even after several repeated attempts,
but the LITE would freeze every time when the upload reached around 2GB.
I suspect there might be an issue with the LITE's USB chip or protocol.
Because as for Nintendo, I wouldn't find it strange at all if they used non-standard USB protocols or chips for the LITE.
I will try to find a few non-Lite users to conduct tests and see.

**Comment by ITotalJustice** [comment]
Ah yeah I forgot that the example code does not have the dev/null mount, only the SD card.

If you use sphaira mtp, it has a dev/null mount which is used for speed testing. If it fails there as well, then that's very interesting.

**Comment by TOM-BadEN** [comment]
I just tested dev/null with LITE via sp, and it succeeded.
I uploaded a single 3GB file without any issues,
though I couldn't see the specific speed.
Then I tested a single 1.5GB file on sp's SD mount point,
and it got stuck while creating the file. After waiting for about 2 minutes,
the computer made a beeping sound, and the upload was interrupted.

**Comment by ITotalJustice** [comment]
this is the mount i am talking about:

<img width="793" height="344" alt="Image" src="https://github.com/user-attachments/assets/0c4c0dcc-fe9e-4de2-b723-b591baff69cb" />

its a "fake" upload where it just reads the usb as fast as possible, so it doesn't block.

my theory is that windows doesn't like a transfer taking too long, and seems to hang if the data its trying to send takes too long. Or, somehow it is sending a command, maybe via the control endpoint and its waiting for that to be handled. idk. i don't see anything in the mtp/ptp spec about this, but it is a very big spec so maybe i missed something.

anyway, if its *also* fails to upload to the "DevNull" mount, then that rules out windows not like transfers taking too long.

**Comment by TOM-BadEN** [comment]
```
Result CreateFile(const char* path, s64 size, u32 option) override {
    return fsFsCreateFile(&m_fs, FixPath(path), size, option);
}
```

When testing with the Switch Lite, I also noticed a phenomenon:

I modified the "size" parameter in the file creation function within the example to 0, and now uploading a single file under 1.5GB can be stably successful. However, if I upload this same file again right after a successful 1.5GB upload, the process will get stuck when the upload reaches around 1GB.

In addition, I prepared a folder containing 49 compressed packages, with a total size of only 7KB. First, I dragged this entire folder to the SD card, and then tried to upload a single 500MB file. This 500MB single file tends to randomly get stuck halfway through the upload (it happens with a certain probability).

I also tested repeatedly uploading this 500MB single file without closing MTP. After approximately 5 attempts, the upload got stuck when it reached 90MB.

**Comment by ITotalJustice** [comment]
Have you tested the DevNull?

**Comment by TOM-BadEN** [comment]
In addition, I found another problem.
Suppose I have uploaded a folder with the internal structure:
A folder/B folder/1.txt
I renamed A to C, and the renaming was successful.
However, if I try to rename B or 1.txt again, it doesn't work. I think this might be because the internal path isn't synchronized.

I tested the SP, and it also has this problem.

**Comment by TOM-BadEN** [comment]
I just tested with SP's DevNull.
I uploaded the same 1.5GB single file three times repeatedly without any issues.
For the fourth time, I directly uploaded a 3GB single file, and there was still no problem.

**Comment by ITotalJustice** [comment]
I have pushed a branch called "logs" https://github.com/ITotalJustice/libhaze/tree/logs. It has logs enabled (like sphaira, its the same code) and write them to `/libhaze_log.txt`. If you could please build the example for it and then try and cause libhaze to hang during a file transfer, then upload the logs here.

Note: you won't be able to open the logs file whilst libhaze example is open, so you must use ftp or sphaira mtp to read the log file after.

```sh
git checkout logs
cmake --preset MinSizeRel
cmake --build --preset MinSizeRel
nxlink build/MinSizeRel/libhaze-example.nro -a 192.168.1.101
```

**Comment by TOM-BadEN** [comment]
Got it, I'll upload it here later, and it will be done no later than half a day from now.

**Comment by TOM-BadEN** [comment]
[MTP_LOG.zip](https://github.com/user-attachments/files/22369237/MTP_LOG.zip)

The testing has ended, but the results made me dizzy — I don’t know what exactly happened.
I ran a total of 5 rounds of testing.

The testing sequence was:

Without modifying the file creation function: Round 1

With the file creation function modified: Rounds 2 and 3

Up to this point, the results were consistent with my tests yesterday:

Without modifying the file creation function → the program gets stuck when creating a file.

With the file creation function modified → the program gets stuck during writing.

I thought I’d do an extra round of testing without modifying the file creation function,
so I reverted the changes, recompiled,
and surprisingly, all the tests succeeded:

425 MB file, uploaded 10 times → success

1.5 GB file, uploaded 9 times → success

3 GB file, uploaded 3 times → success

This is just too strange.

So I ran another round of tests:

Uploaded 425 MB, 1.5 GB, and 3 GB files in sequence → all succeeded.

Selected all three files at once and uploaded together → all succeeded.

I’m completely baffled by this.

Each log represents one test, and each log corresponds to one full restart of the program.
I’ve marked the folder names.
After a freeze, it always ended with a timeout, and I closed the plugin myself.

**Comment by ITotalJustice** [comment]
Thank you so much for running those tests and the logs, as well as naming them. That's very helpful to have!

The same issue is happening in all of those logs, i'll explain here (it's going to be a little verbose, but this is so i don't forget):

---

To find where it freezes in the log, its best to scroll all the way to the bottom and find the last 2 events that have a huge time difference. Example:
```txt
[01:15:34] -> Waiting for transfer completion...
[01:15:34] -> Waiting for 1 waiters + 1 internal waiters
[01:15:34] -> Waiting for 2 total waiters
[01:15:51] -> Woke up, idx=1
[01:15:51] -> Returning idx=0
[01:15:51] -> Woke up from transfer wait
```
This is location here https://github.com/ITotalJustice/libhaze/blob/e2fd417ca29ad75fa4db8479d53f4977e6cc5606/source/event_reactor.cpp#L54-L75

Every log gets stuck at this location for ~30s until windows kills the transfer.

---

So what is this code doing? Well first it requests 4MiB of data from windows, then it enters this function to wait on the event. The event will fire when either all 4MiB of data is received, or a empty packet (ZLT) is sent to indicate the end of a transfer.

The issue here is that the event is never fired, so it waits forever. However it does *eventually* wake up because windows sends an empty packet (ZLT) to kill the transfer after 30s. But the logs show that when it windows sends the ZLT, this triggers the event, and then the switch reads the 4MiB and *then* it reads the empty packet? So it looks like the switch *did* read the full 4MiB but for some reason it didn't fire the event.

The event has `autoclear=false` meaning that waiting on event does not clear it, it has to be manually cleared. Haze only clears event *after* it has received data, so this is not a case of missing events.

---

The trigger for this bug seems to be related to the time between USB transfers. If the time between 2 USB transfers takes too long, this freeze happens. This is why it happens you don't modify the file create size, because then file create tries to allocate a 1GiB+ file upfront, which can take a few seconds. Whereas when the size is set to 0, it returns instantly.

This is also consistent with why uploading to "DevNull" works because there is no latency between USB transfers.

---

Where this hypothesis starts to fall apart however is the fact that it works fine using USB 3.0 transfers for your switch. With 3.0 transfers, the transfer speed can hit 100MiB+, so this only increases the latency between USB transfers as they complete so quickly. Although this could be a windows driver quirk where. Who knows.

---

At the end you ran all the tests again, and now they all magically pass. This is the issue i found in the past when i had users helping me debug this problem, it would start working for them and none of us knew why.

- I don't think this is switch usb bug, otherwise the same thing would happen for usb installs (not using mtp). And that uses basically the same transfer code as haze...
- This leads me to think is a windows mtp bug, but afaik DBI and Tinfoil do not have this problem, so it can't be that.
- The transfer buffer size is 4MiB, which should be fine. This is what i have always used for USB transfers and haven't had an issue until MTP. [It's noted on switchbrew that 16MiB can cause problems for uploading data from switch -> pc](https://switchbrew.org/wiki/USB_services#PostBufferAsync) however we are reading pc -> switch, and its 4MiB so its not that either...

---

With all that being said, i am back to square one. I don't know where to begin fixing this. I can see *where* it hangs, but i have no idea why. [We could try reduce the transfer buffer to something like 64_KB](https://github.com/ITotalJustice/libhaze/blob/e2fd417ca29ad75fa4db8479d53f4977e6cc5606/include/haze/ptp_responder_types.hpp#L154), but it still doesn't explain *WHY* it's even hanging. I am also not 100% what windows is doing either:
- Is it even sending data?
- If not, *why*? Was it too slow? Did it send a control packet that i need to handle?
- Actually, i can't totally blame windows either as i remember it freezing for someone who was using a Mac, and the client was a wrapper around libmtp, which is the same thing i use on linux.

**Comment by TOM-BadEN** [comment]
Thank you very much for your detailed analysis and answers.

I just did another test a moment ago: I selected three files (425 [units], 1.5GB, and 3GB) at once, dragged them to MTP, and the upload was successful. Then I closed the MTP client, reopened it, and tried again—this time, it failed.

However, this version is much better than the previous one that required setting thread cores. Yesterday, I ran repeated tests many times, and the symptom was very consistent: I never succeeded in transferring the 3GB file even once. Today’s tests have been successful quite a few times, and once a transfer succeeds, it stays successful (as seen in the two test cases: 9 files of 1.5GB each and 3 files of 3GB each).

After reading your analysis, it seems this involves quite in-depth content, which is completely beyond my level. I can’t come up with any ideas on how to fix it; all I can do is cooperate with you for further tests if you have new ideas.

I will try modifying the buffer size to 64k as you suggested and run a test later.

**Comment by TOM-BadEN** [comment]
I used a buffer size of 64KB. After testing, there seemed to be an improvement, but transfer failures still occurred occasionally.

I conducted a total of 3 tests.

Test 1: Dragged a folder at once, which contained 16 compressed packages with a total file size of 19GB.
Result: All files were transferred successfully.

Restarted MTP.

Test 2: Dragged a folder at once, which contained over 20 compressed packages with a total file size of 32GB.
Result: During the transfer, several consecutive files got stuck while being created, and this issue persisted until a timeout occurred. After that, the subsequent files resumed normal creation and writing.

Restarted MTP.

Test 3: Dragged a folder at once, which contained over 20 compressed packages with a total file size of 32GB.
Result: This time, the transfer was highly successful—all files were written successfully.

Although not all 3 tests were fully successful, there was indeed a significant improvement. This is because, compared to the initial stage, I tried writing a 3GB file at least 20 times back then, and not a single attempt succeeded.

It’s possible that reducing the buffer size further could bring a slight improvement. However, I  guess the buffer size is not the root cause of the problem; further reduction can only mitigate the issue rather than completely eliminate it. Besides, 64KB is already small enough, so I didn’t proceed to test with 32KB.

**Comment by ITotalJustice** [comment]
Thanks. I'm glad that it still fails even with the buffer size change because that would've confused me further if it had worked.

One last thing to try is to make the freeze always be reproduceable.

It sometimes fails during the sd card upload because the delay between usb transfers. What we could try is increase the delay further by adding a svcSleepThread() before writing the file to the SD card. This in theory should cause mtp to always freeze.

If that works, or at least increases the changes of it failing, then we should be able to get DevNull to fail by simulating the sd card slow write speed.

If you'd be willing to test this, I'll push some changes tomorrow.

I forgot to ask, what windows version / update are you using? And is it the same for your friend? I am going to try and cause this freeze tomorrow but I only have a VM to test so it may not be possible to replicate. Thanks again for your help.

Oh, are you using emummc? And is it file based or partition? And what fw and ams version? Is it the same for your friend?

I don't have a switch lite, but I want to match your setup as closely as possible 😅

**Comment by TOM-BadEN** [comment]
Windows 11 Version 23H2 (OS Build 22631.5624)
AMS:  1.9.3
FW: 20.1.5
partition
switch lite

This is my configuration. 
I don't know my friend's configuration yet.
I'll ask him for it. Thank you very much. 
I will cooperate with you in relevant tests.

**Comment by ITotalJustice** [comment]
I've made some improvements to libhaze by adding support for read-only filesystems (although kde-kio6 ignores it, as well ad many other bugs i found with kio6...) and timestamps, so copying files from the switch should perverse the create and modify date.

In the branch here https://github.com/ITotalJustice/libhaze/tree/delay i've added the delay i mentioned. Here is the delay value if you want to mess around with it https://github.com/ITotalJustice/libhaze/blob/553aee34f4c847d967bc2d97b3589a1c961adaf8/example/source/main.cpp#L66

I have it set to 100ms. this is applied before every file create, read, write. If you want to set it so 1s, it would be `1e+9`. 5s would be `5e+9`. 10ms would be `10+e7` etc.

**Comment by TOM-BadEN** [comment]
Got it. I’ll test it and provide feedback here afterwards.

**Comment by TOM-BadEN** [comment]
[delay-log.zip](https://github.com/user-attachments/files/22394647/delay-log.zip)

Each item ends with an MTP restart.
After a file creation freeze, I always wait for the timeout to recover before exiting the program.

Test sequence and results are as follows:

Round 1: 100 ms

Item 1: Upload 1.5 GB file → freeze during file creation ❌

Item 2: Upload 1.5 GB file → freeze during file creation ❌

Item 3: Upload 425 MB file → freeze during file creation ❌

Round 2: 10 ms

Item 1: Upload 425 MB file → success ✅

Item 2: Upload 15 × 425 MB files → success ✅

Item 3: Upload 5 × 1.5 GB files → success ✅

Item 4: Upload 32.1 GB (20 files total) → success ✅

Item 5: Upload 32.1 GB (20 files total) → freeze during creation of the 13th file ❌

Round 3: 1000 ms

Item 1: Upload 1.5 GB file → freeze during file creation ❌

Item 2: Upload 425 MB file → freeze during file creation ❌

Round 4: 2 ms

Item 1: Upload 1.5 GB file → freeze during file creation ❌

Item 2: Upload 425 MB file → success ✅

Item 3: Upload 1.5 GB file → success ✅

Just now, I quickly tested several more times at 1000 ms, and all of them froze during file creation. Unfortunately, I didn’t keep the logs.
It’s a pity — during the 10 ms tests, I really thought it was going to succeed, but in the end, it still failed. This damned randomness.

**Comment by ITotalJustice** [comment]
Thanks again.

From the tests, it looks like the delay between usb transfers is whats causing the freeze, as shown by 100ms and 1000ms *always* failing, whereas a reduced delay of 10s and below sometimes works.

It is possible to workaround this, i think.

1. Instead of allocating the file size upfront, set the size to 0 and let the file grow over time. This is the same fix you tried before and always worked. This results in slightly slower writes, however as we are writing in large 4MiB chunks, this really isn't an issue and is only noticeable when writing small chunks, such as 16KiB where the file has to constantly grow.
2. As file transfers are multi-threaded, the write thread can see if the buffer is full. Normally it would just wait on an event which gets signalled when there's space in the buffer (ie, the read thread has drained the buffer). Instead, if the buffer is full, keep filling it but at small increment. For example, read 1KiB every 1ms which is an effective transfer rate of 1MiB/s. When the buffer becomes empty / half empty, transfer like normal.

So 2. would basically be a "slow mode" where we constantly pull data from usb. I think this is a hack and surely isn't the correct way to solve this. There's no way every MTP responder out there works around this "freeze" on windows by having a slow mode. 

I'll breakdown my findings from the log.

---

## Logs Delay

Comparing all the logs where the file create failed shows that on the times that file create succeeded, it was because the file was created *instantly*. Eg:
```txt
[04:39:59] -> Registering object 87 (//mods2/0000-add-mod-0000/1.5TEST/THIS IS 1.5 GB-1.zip)
[04:39:59] -> Prepared to receive object 87 (//mods2/0000-add-mod-0000/1.5TEST/THIS IS 1.5 GB-1.zip) of size 1633636236
```
And
```txt
[05:31:22] -> Registering object 83 (//mods2/0000-add-mod-0000/THIS IS 425MB.zip)
[05:31:22] -> Prepared to receive object 83 (//mods2/0000-add-mod-0000/THIS IS 425MB.zip) of size 446488893
```

It *always* failed when it took 3s+.
```txt
[04:17:02] -> Registering object 84 (//mods2/0000-add-mod-0000/THIS IS 1.5 GB.zip)
[04:17:12] -> Prepared to receive object 84 (//mods2/0000-add-mod-0000/THIS IS 1.5 GB.zip) of size 1633636236
```
And
```txt
[05:29:02] -> Registering object 83 (//mods2/0000-add-mod-0000/THIS IS 1.5 GB.zip)
[05:29:08] -> Prepared to receive object 83 (//mods2/0000-add-mod-0000/THIS IS 1.5 GB.zip) of size 1633636236
```
And
```txt
[05:23:23] -> Registering object 84 (//mods2/0000-add-mod-0000/425test/THIS IS 425MB 2 (1).zip)
[05:23:26] -> Prepared to receive object 84 (//mods2/0000-add-mod-0000/425test/THIS IS 425MB 2 (1).zip) of size 446488893
```

I'm guessing the reason the file create (1.5G+) can succeed immediately is because the fs driver must be caching recently deleted sectors. I've noticed this when allocating a 16gb file which takes a long time, then delete it, then allocating it again immediately causes it to take 0s. So this is why creating the file sometimes works / fails.

## Logs Modified Create (0 size)

The timeout here is consistent with the above. Here's an example of a transfer timing out. Its a little long, but notice the first and last line. This is the time between USB transfers.
```txt
---> [01:11:21] -> Starting async transfer of 4194304 bytes on endpoint 0
[01:11:21] -> Waiting for transfer completion...
[01:11:21] -> Waiting for 1 waiters + 1 internal waiters
[01:11:21] -> Waiting for 2 total waiters
[01:11:21] -> Woke up, idx=1
[01:11:21] -> Returning idx=0
[01:11:21] -> Woke up from transfer wait
[01:11:21] -> Getting transfer result for URB ID 37393 on endpoint 0
[01:11:21] -> Transfer complete: requested 4194304 bytes, transferred 4194304 bytes same: 1
[01:11:21] -> ReadBuffer: flushed, got 4194304 bytes left: 12
[01:11:21] -> Received 1048576 bytes
[01:11:21] -> SetWriteBuf: waiting for space...
[01:11:22] -> Wrote 1048576 bytes at offset 41943040
[01:11:22] -> Writing 1048576 bytes at offset 42991616
[01:11:22] -> SetWriteBuf: got space!
[01:11:22] -> Reading up to 1048576 bytes at offset 46137344
[01:11:22] -> Received 1048576 bytes
[01:11:22] -> SetWriteBuf: waiting for space...
[01:11:23] -> Wrote 1048576 bytes at offset 42991616
[01:11:23] -> Writing 1048576 bytes at offset 44040192
[01:11:23] -> SetWriteBuf: got space!
[01:11:23] -> Reading up to 1048576 bytes at offset 47185920
[01:11:23] -> Received 1048576 bytes
[01:11:23] -> SetWriteBuf: waiting for space...
[01:11:24] -> Wrote 1048576 bytes at offset 44040192
[01:11:24] -> Writing 1048576 bytes at offset 45088768
[01:11:24] -> SetWriteBuf: got space!
[01:11:24] -> Reading up to 1048576 bytes at offset 48234496
[01:11:24] -> Received 1048576 bytes
[01:11:24] -> SetWriteBuf: waiting for space...
[01:11:25] -> Wrote 1048576 bytes at offset 45088768
[01:11:25] -> Writing 1048576 bytes at offset 46137344
[01:11:25] -> SetWriteBuf: got space!
[01:11:25] -> Reading up to 1048576 bytes at offset 49283072
[01:11:25] -> ReadBuffer: flushing to get more data: 12
[01:11:25] -> Reading 4194304 bytes
---> [01:11:25] -> Starting async transfer of 4194304 bytes on endpoint 0
```
So for some reason, the write speed of the sd card dropped down to 1MiB/s. Because of this, it took 4s to flush the 4MiB USB buffer, so windows likely timed out.

Here's another log you provided which shows the same thing:
```txt
--> [01:31:24] -> Starting async transfer of 4194304 bytes on endpoint 0
[01:31:24] -> Waiting for transfer completion...
[01:31:24] -> Waiting for 1 waiters + 1 internal waiters
[01:31:24] -> Waiting for 2 total waiters
[01:31:24] -> Woke up, idx=1
[01:31:24] -> Returning idx=0
[01:31:24] -> Woke up from transfer wait
[01:31:24] -> Getting transfer result for URB ID 36385 on endpoint 0
[01:31:24] -> Transfer complete: requested 4194304 bytes, transferred 4194304 bytes same: 1
[01:31:24] -> ReadBuffer: flushed, got 4194304 bytes left: 12
[01:31:24] -> Received 1048576 bytes
[01:31:24] -> SetWriteBuf: waiting for space...
[01:31:25] -> Wrote 1048576 bytes at offset 3246391296
[01:31:25] -> Writing 1048576 bytes at offset 3247439872
[01:31:25] -> SetWriteBuf: got space!
[01:31:25] -> Reading up to 1048576 bytes at offset 3250585600
[01:31:25] -> Received 1048576 bytes
[01:31:25] -> SetWriteBuf: waiting for space...
[01:31:26] -> Wrote 1048576 bytes at offset 3247439872
[01:31:26] -> Writing 1048576 bytes at offset 3248488448
[01:31:26] -> SetWriteBuf: got space!
[01:31:26] -> Reading up to 1048576 bytes at offset 3251634176
[01:31:26] -> Received 1048576 bytes
[01:31:26] -> SetWriteBuf: waiting for space...
[01:31:27] -> Wrote 1048576 bytes at offset 3248488448
[01:31:27] -> Writing 1048576 bytes at offset 3249537024
[01:31:27] -> SetWriteBuf: got space!
[01:31:27] -> Reading up to 1048576 bytes at offset 3252682752
[01:31:27] -> Received 1048576 bytes
[01:31:27] -> SetWriteBuf: waiting for space...
[01:31:28] -> Wrote 1048576 bytes at offset 3249537024
[01:31:28] -> Writing 1048576 bytes at offset 3250585600
[01:31:28] -> SetWriteBuf: got space!
[01:31:28] -> Reading up to 1048576 bytes at offset 3253731328
[01:31:28] -> ReadBuffer: flushing to get more data: 12
[01:31:28] -> Reading 4194304 bytes
--> [01:31:28] -> Starting async transfer of 4194304 bytes on endpoint 0
```
Again, the writes drop to 1MiB/s so it times out after 4s of inactivity.


Do you maybe have a FTP or any sysmodule thats running in the background thats reading/writing files to the sd card?

---

Anyway, i am now 100% sure that it's a timeout issue. I don't know why windows freezes the way it does, as in, why doesn't it just cancel the transfer immediately rather than waiting 30s to do so. I am also not sure why the sd card drops to such a low write speed, although it explains why i cannot reproduce this bug, because the speed remains a constant 24MiB/s.

I can push some changes tomorrow to add a delay between each usb read during a transfer, and reduce the buffer size. For example, read 4KB every 5ms for a transfer rate of just under 1MiB/s. This will be very slow, but it shouldn't timeout at all because we constantly read data.

If that works, i'll do a proper fix. Thanks again, i had completely given up on this issue, but now it looks fixable.

**Comment by TOM-BadEN** [comment]
I’m really glad to see progress on this issue, and I truly appreciate your detailed analysis report.
If this problem can be fixed, that would be amazing. For an amateur AI tinkerer like me, I would have no way of integrating the MTP feature without your project.


Also, I’ve indeed been running an FTP background program — your FTPSV.
However, during the MTP transfer, I wasn’t actually using it for file transfers.
Oh, I just remembered — even though I wasn’t using it to transfer files, my FTP client FileZilla on the PC was running in the background. I usually keep it open since I rely on it for transferring modified programs and testing logs.

I’m not sure whether FileZilla, when idle, might still perform read/write operations on the SD card. From what I recall, FTPSV automatically disconnects after a short interval of inactivity.


When your new test build is available, I’ll run the tests again with FTP fully closed.

**Comment by ITotalJustice** [comment]
Ah okay. Yeah the ftp server wouldn't have caused it to slow down, especially when idle.

I have thought of a few possible reasons for the SD card slow down:
1. Maybe the fs driver took a very long time to allocate the next 1MiB chunk, as the file size grows on each write. I always allocate file size when creating the file so I personally don't know how common that is.
2. As you're using emuMMC, maybe the os is r/w to some system save files which is now slowing down the SD card.

I think 1 is more likely because I don't see what the OS could be doing that takes 4s+ to complete. Then again I don't use emuMMC so I'm not sure.

I have another idea. Instead of adding a delay, or a slow mode, instead I can reduce the file buffers from 1mb to 64k and do the same for the usb buffer. In theory, this should reduce the MAXIMUM file write time by 16x, at the cost of more sys calls, but the transfer should be stable.

This shouldn't effect write speed all that much, and we can fine tune the buffer size (128k, 256k, 512k) and see which is the biggest size we can get away with, or even make it user configurable.

For file uploads (switch to pc) we can keep the buffer size at 4mb as this maximises the sd card/eMMC throughput and doesn't suffer from the file allocation slow down as it's just simply reading a file.

**Comment by ITotalJustice** [comment]
I've pushed changes to the `logs` branch. I haven't tested the code, but it should work. I hope it also fixes the timeout.

The changes are:
1. Do not allocate the file size upfront (the change you made initially).
2. Reduce write buffer size to hopefully reduce latency between USB transfers (what i suggested above).

**Comment by TOM-BadEN** [comment]
Got it.
I’ll come back with feedback after testing.
But it will probably be in the evening, since I have to go out for a while.

I have a feeling this time the problem can be solved.    :)

**Comment by ITotalJustice** [comment]
Good news! I can reproduce the freeze on windows 11 (vm), and reliably as well. I found a quicker way to test how long until a hang happens by adding a delay to the CreateFile function. Making it take 3s almost always makes it freeze. Anything above always freezes. I performed these tests by transferring 20 empty (0 size) files which hang on the first or second file create when delaying by 3s, whereas it always freezes on the first file delaying by 5s.

This is quite problematic to handle for game installing, due to creating a NCA placeholder requires allocating the file size upfront, same as the CreateFile. This can trigger the freeze. Also if installing NSZ, it can be heavily compressed so it would not request any data for a long time, again causing the freeze. Ugh, looks like i would need to implement a slow mode so that the usb will always request data and never block. If the timeout is ~3s, then i could just request a packet (max 1024 for USB 3.0) every 1s, or probably every 100ms just to be safe. This would be 10KiB/s which will never overflow the buffer, and i could always abort if the buffer size grew to a crazy amount.

So all of this is fixable, just a bit of a pain to do so. I can still optimise for allocating the file size up front as well, i could just set the file size in the file write thread on the first pass, so that way it doesnt block, and the read thread can just run at 10KiB/s.

**Comment by TOM-BadEN** [comment]
Congratulations, another step forward — getting closer to a fix.

**Comment by TOM-BadEN** [comment]
I tested the latest log build,
the one with 64+64 KB + 0-size buffer.
Since it’s still running, I don’t have logs yet,
and I probably won’t be able to run too many test rounds anyway, because it’s really too slow.

With the previous version (64+1 MB + pre-allocated file), my write speed was around 33–35 MB/s.
With the current version, using a stopwatch, I measured about 5.5 MB/s.

However, compared to my earlier test observations, I noticed something:
Previously, when I tested with 0-size, there was a high chance that writing would suddenly stop, then jump ahead twice, and then completely freeze until a timeout.

But with the current version, I’ve already written 10 items totaling around 20 GB.
Although there are still moments where writing suddenly slows down, it doesn’t freeze — instead, it continues to increase slowly and then recovers back to the original speed.

This observation matches your earlier analysis perfectly.

**Comment by ITotalJustice** [comment]
Great! Yeah the slow speed is why I had used such large buffers and allocated the file upfront, it's the only way to get good write speed for the SD card.

I'll work on adding a automatic slow mode for when the buffer is full. This way we will still get the same speed as before, but it will handle the case where sd card slows down or Create file takes too long.

It wouldn't however fix the freeze if the user presses the home button in the middle of a transfer. I don't think that's fixable anyway unless we block the home button.

**Comment by TOM-BadEN** [comment]
Awesome, I’m really looking forward to your new version.
As for the HOME button, personally I don’t think it’s something worth worrying about.
I can’t imagine users intentionally pressing the HOME button during a transfer.
And even if they do, they’ll quickly realize it was a mistake and won’t repeat it.
At worst, it would only invalidate that particular transfer — it wouldn’t cause any irreversible issues.

**Comment by ITotalJustice** [comment]
More good news. I can trigger the freeze in DBI by pressing the home button during a transfer and waiting 3s. This happens in all versions.

So it looks like we are on the right path to fixing it!

**Comment by TOM-BadEN** [comment]
It’s indeed good news — everything is moving in the right direction.  ;)

**Comment by ITotalJustice** [comment]
I believe i have fixed the bug. The fix is in the logs branch. Please let me know if it works for you as well as the transfer speed. It should be roughly the same as it was originally, maybe slightly slower but nothing like 5MiB/s.

There is still one possible bug. When the file transfer has finished, there is supposed to a response sent from the switch. However, if the last file write takes too long, then it'll timeout again when it tries to send the command. A solution to this is to send the success command when the file has finished reading, so there's no delay. However this would cause a new problem where if i report the file upload a success, but then it fails writing the last chunk, there's no way to tell windows it actually failed.

Idk how to handle that last bit. I may just leave it as it's very unlikely to freeze during the last file write, and even if it does, the write was actually successful so even if windows freezes, it's not the end of the world.

**Comment by TOM-BadEN** [comment]
Great! Thanks for your hard work. Once I finish what I have on hand, I’ll start testing.
I’ll run at least 3–4 rounds, each round with 32GB (20 files total), to verify.
Since in previous tests the best result was only being able to complete one round, I think this amount of testing should be sufficient.

**Comment by TOM-BadEN** [comment]
[libhaze_log.txt](https://github.com/user-attachments/files/22415728/libhaze_log.txt)

I just tested the latest log version.
During the second round of testing, an error occurred.

From what I saw in the console, it suddenly froze for a while, then suddenly popped up a message showing how much had been written and the size, but the size value was incorrect. Then I kept waiting. After the computer beeped, the next file showed the same symptom, so I stopped.
I don’t remember the exact number, and I instinctively exited the program.



The place where the log file shows a timestamp change is between
This is the point where it first started to freeze.
178262–187263
06:21:18-06:22:51

```
[06:21:18] -> Both threads finished
[06:21:18] -> Received object 89 (//mods2/0000-add-mod-0000/TEST222/THIS IS 1.5 GB - 2 (2).zip), total size 3407904

[06:21:18] -> Writing 12 bytes
[06:21:18] -> Starting async transfer of 12 bytes on endpoint 1
[06:21:18] -> Waiting for transfer completion...
[06:21:18] -> Waiting for 1 waiters + 1 internal waiters
[06:21:18] -> Waiting for 2 total waiters
[06:22:51] -> Woke up, idx=1
[06:22:51] -> Returning idx=0
[06:22:51] -> Woke up from transfer wait
[06:22:51] -> Getting transfer result for URB ID 24289 on endpoint 1
[06:22:51] -> Transfer complete: requested 12 bytes, transferred 12 bytes same: 1
[06:22:52] -> ReadBuffer: flushing to get more data: 12
[06:22:52] -> Reading 1048576 bytes
[06:22:52] -> Starting async transfer of 1048576 bytes on endpoint 0
[06:22:52] -> Waiting for transfer completion...
[06:22:52] -> Waiting for 1 waiters + 1 internal waiters
[06:22:52] -> Waiting for 2 total waiters
[06:22:52] -> Woke up, idx=1
[06:22:52] -> Returning idx=0
[06:22:52] -> Woke up from transfer wait
[06:22:52] -> Getting transfer result for URB ID 352097 on endpoint 0
[06:22:52] -> Transfer complete: requested 1048576 bytes, transferred 32 bytes same: 0
```
There were also changes in the following positions:
178213–178214
178240–178241

**Comment by ITotalJustice** [comment]
That freeze is very strange. So it starts to set the file size (1.5G) at `06:19:45` and it doesn't finish until `06:20:06` 👀. Even stranger is that when the last slow read happens before the freeze:
```
[06:19:46] -> Transfer complete: requested 1024 bytes, transferred 1024 bytes same: 1
```
the thread just...does nothing. it never wakes up. After that log, it just returns from the function and then it should then log this:
https://github.com/ITotalJustice/libhaze/blob/2a3bd3add49be8dbcb17e20b0fd3475abade2b1a/source/ptp_responder_ptp_operations.cpp#L534
however it gets stuck until `[06:20:06]`...

Sooooooo i can only guess that the log file just so happens to flush to file, which is blocked because the sd card file allocate is still happening.

I have pushed a change that disables logs by default and reduces the usb read spam to just 2 reads per second during slow mode, rather than 100.

**Comment by TOM-BadEN** [comment]
Got it. I’ll run another test right away.

**Comment by TOM-BadEN** [comment]
This time, the very first file showed exactly the same symptom,
but since logging was disabled by default, no log was recorded.
I found that the size in the picture is also abnormal, exactly the same as before.

<img width="734" height="203" alt="Image" src="https://github.com/user-attachments/assets/3c155544-a339-44f3-ba6c-61972fdccd09" />

**Comment by ITotalJustice** [comment]
The size is the size of the buffer being written. The normal size is 1MiB. In that example, it's a combination of the buffered data during a slow read and half of a transfer that windows sent before it froze. I think the size is actually 262176. The extra 6 at the end is because `printf("\r")` doesn't actually clear the line, it just sets the cursor to the same line, so like:
```
1048576
262176
```
and thats why theres an extra 6.

Anyway, i am really stumped here. I don't know what else to try. If the logs are disable then the read thread should never block. Maybe the OS scheduled the usb thread on the same write thread? I could set dedicated cores...but i dont know. It looks like the whole OS has locked up or something. Can you still press the home button when it freezes?

I've pushed another change that creates dedicated threads for r/w. It should still fail. I'd be even more confused if it doesn't 🥲

**Comment by TOM-BadEN** [comment]
This is really a strange and frustrating bug. Unfortunately, my skills are limited, so I can’t provide any ideas on how to fix it.
I’ve already gone out, I’ll test it in the evening and give feedback then.

**Comment by ITotalJustice** [comment]
> This is really a strange and frustrating bug. Unfortunately, my skills are limited, so I can’t provide any ideas on how to fix it
No worries, you have been a great help testing all this for me.

I did find a bug where i was unlocking a mutex twice during every r/w transfer (i have pushed a fix). I don't think that would have anything to do with the freeze, but idk at this point. The bug was introduced in https://github.com/ITotalJustice/libhaze/commit/23889ddfbcc3772f3b3dd448d20c9b151c2a3ac0, so the commit that added slow mode.

**Comment by TOM-BadEN** [comment]
I just finished the test,
and I still ran into the exact same write freeze as yesterday.

I’ve already moved on to the second round of testing, and it’s almost finished, but unexpectedly the freeze still occurred in the end.
I also tested the HOME button — it can immediately exit the program and disconnect MTP.

**Comment by ITotalJustice** [comment]
Are you using exFAT? Have you been able to cause this freeze using DBI / Tinfoil MTP?

Im really out of ideas now. I have pushed a change which removes the file size alloc. This will make writes slower but should start immediately. The switch should show `TEST v8` as well, just to make 100% it is the latest version being tested.

If that works, i do not know why. If it doesn't work, then i also don't know why. I'm completely baffled by this.

**Comment by TOM-BadEN** [comment]
I’m using FAT32, and I’ve never used Tinfoil MTP.
I’ll first test with DBI, because I’ve never had any issues using DBI, so I haven’t tested it before.

**Comment by TOM-BadEN** [comment]
Oh no!
DBI actually froze when creating a file! 😱

Previously, I only used DBI to install games. For small files I used FTP, and for large files I usually transferred them directly through Hekate. I’ve never used DBI to transfer a single large file before.

My bad—I subconsciously assumed DBI was fine and thought it was a libhaze issue. I’m really sorry for making you do so much useless work and wasting your time. TwT

**Comment by ITotalJustice** [comment]
Oh no, that's good news! Well for me it is 😄 At least we can somewhat rule out libhaze being at fault.

You haven't wasted my time at all. I was able to trigger the freeze/timeout bug as well but we fixed it with slow mode. However, now a new bug seems to happen when setting the file size which seems to freeze the both the read and write threads. Btw, i don't suppose you're using a modified atmosphere? 

There are a few things to try, if you want:
- Check if this happens on sysMMC (just test libhaze here as it's completely safe to use).
- Disable all sysmodules (including sys-patch) by moving them to a folder called `contents-backup` and restart your switch.
- I did push some changes which now disable the SetFileSize(). Would you mind testing that? It's in the logs branch `git pull` to update. The version displayed on the switch should say `TEST v8`.
- If the sd card has less than 15% space left, try freeing up some space.
- Try using airplane mode when performing the test.
- If *all* the above still fails, if you have a spare sd card, try using that? You would just need atmosphere + libhaze, no need to setup emuMMC This is a big ask so i understand if you don't want to try this option.

I understand that's a lot to ask. If you do manage to test some/all of that, i'd really appreciate it.

**Comment by TOM-BadEN** [comment]
I just tested version v8 (It’s still the original testing environment.). One of the files froze during writing, but after the timeout, the other files were written normally.

My atmosphere is using an 8GB module because I modified the hardware to better use mods on 20FW. I’m not sure if this will have any effect. As far as I know, many people upgraded to 8GB memory after 20FW, and I’ve also heard that even if you revert back to a 4GB module, some things might still behave differently—this part I don’t fully understand.

My SD card is a SanDisk 512GB “Red & Gold” (dual-color red and gold), with 73.8GB free space currently.

Does sysMMC refer to the NS’s NAND? If so, I can use it.

I can also temporarily remove sysmodules if needed.

For SD card space, I can delete some games to reach about 100GB free.

Airplane mode is not an issue.

However, I don’t have any other SD cards, because I don’t use SD cards for anything else besides the NS, so I only have this one.

**Comment by ITotalJustice** [comment]
> My SD card is a SanDisk 512GB “Red & Gold” (dual-color red and gold), with 73.8GB free space currently.

Okay the free space is fine, and the sd card is good.

> Does sysMMC refer to the NS’s NAND? If so, I can use it.

Yes. Basically not using emunand. I highly doubt that is the problem, especially as it's partition mode (file emunand has problems and is awfully slow), but it's just another variable to rule out.

> I can also temporarily remove sysmodules if needed.

Yes please.

> My atmosphere is using an 8GB module because I modified the hardware to better use mods on 20FW

That is interesting, i forgot that was a thing. I do not know much about these 8GB upgrades or the modified atmosphere, but is it possible to run stock atmosphere and be limited to 4GB? Or does it have to be modded for it to even boot?

**Comment by TOM-BadEN** [comment]
However, I don’t know how to use the NS’s NAND, so I might need your guidance.
I will replace it back with the 4GB “atmosphere” module, but I’ve heard that after upgrading to 8GB, some parts (I don’t remember exactly which) may have been permanently changed.

For free space, I just deleted two games, so there are now 116GB available.

**Comment by TOM-BadEN** [comment]
I have now:

Reverted to the 4GB module

Disabled all sysmodules, including Tesla

Have 116GB of free memory

Enabled airplane mode

After rebooting the NS, I will now proceed with testing version v8.

**Comment by TOM-BadEN** [comment]
Three times!
Three consecutive successes!
best test before was getting stuck in the second round.

**Comment by TOM-BadEN** [comment]
Great! I ran multiple rounds of testing.
Each round was a one-time upload of 32 GB, split into 20 files, repeated three times.
All of them succeeded.

I then restored the sysmodules,
restored Ultrahand’s ovloader + network,
and restored the 8 GB Atmosphere module.

Everything still worked successfully.

Before disabling those components, I had also tested once on V8, and it failed.
Compared with the final environment where the 8 GB Atmosphere module was restored, the only difference was the available SD card space (73.8 GB).

So based on the current testing, it seems the cause of the occasional write freeze was insufficient free space.

:)

Now I can finally transfer completely normally.
I’m really happy, and very grateful for your fix and help.

**Comment by ITotalJustice** [comment]
I'm so relieved that it works now 😄 Thanks for being so thorough with the testing.

the V8 removed the SetFileSize, so the writes would be slowly increasing the file size in each write. I have re-enabled allocating the file size upfront in V9. This will be the final version that i will also merge with Sphaira. I'll also reach out to SciresM about this issue as well as it affects normal Haze as well.

If you would like to test V9, that would be great. However it's probably not needed as I am confident that this issue is now resolved.

**Comment by TOM-BadEN** [comment]
I’ll be using V9.
Once I’ve wrapped up the things I’m working on, I’ll integrate the latest version into my project.
Many thanks to you and the Atmosphère team for your contributions.
:)

**Comment by ITotalJustice** [comment]
I have pushed a fix for a bug that i introduced when i implemented slow mode. The first 1MB-12B would be missing from the file. This was caused by me ~~being dumb~~ forgetting that haze always reads 1MB. So it was reading the 12B packet at the start of the transfer, and then the first 1MB of the file. However i would simply discard that data and start anew. So that data was missing.

This is fixed now. `git pull` to get the changes.

**Comment by TOM-BadEN** [comment]
I tested the latest SP and V9.
The testing method was still dragging in a total of 30 GB, 20 files at once.

SP froze during writing in the second round of testing.

V9 also froze in the second round, and the log I have is from V9.

With SP, enabling logging causes MTP to load slowly.

I’m testing V8 again now.
Previously, V8 successfully passed three rounds of testing under various environments.
I’m re-running the tests to verify once more.

[libhaze_log.txt](https://github.com/user-attachments/files/22448606/libhaze_log.txt)
